import Image from "next/image";
import { Header } from "@/components/Header";
import { ProductCard } from "@/components/ProductCard";
import { SnackArt } from "@/components/SnackArt";
import { FAQ } from "@/components/FAQ";
import { products } from "@/data/products";
import { bundles } from "@/data/bundles";
import { siteConfig, waLink } from "@/config/site";

const rp = (n:number) => new Intl.NumberFormat("id-ID", {style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const orderUrl = waLink("Halo KriukLagi 👋 Saya mau pesan snack!");

export default function Home() { return <><Header /><main>
  <section className="hero" id="beranda"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">✦ SNACK ENAK, SETIAP SAAT ✦</p><h1>Sekali <span>Kriuk,</span><br />Mau Lagi.</h1><p className="lead">Teman ngemil yang renyah, gurih, dan bikin nagih. Cocok buat nemenin semua momen kecilmu.</p><div className="hero-buttons"><a className="button" href={orderUrl} target="_blank" rel="noreferrer">Pesan Sekarang <b>→</b></a><a className="text-link" href="#produk">Lihat Produk <b>↓</b></a></div><div className="hero-notes"><span>✦ Renyah</span><span>✦ Bumbu melimpah</span><span>✦ Mulai 10 ribuan</span></div></div><div className="hero-visual"><div className="sunburst" /><div className="hero-circle"><SnackArt variant="orange" /></div><div className="hero-sticker">Gurih<br />Bikin Nagih! <b>✦</b></div><div className="hero-chip chip-one">Kriuk!</div><div className="hero-chip chip-two">💥</div></div></div></section>
  <section className="products section shell" id="produk"><div className="section-heading"><p className="eyebrow">YANG LAGI BIKIN NAGIH</p><h2>Pilih Kriuk<br /><span>Favoritmu</span></h2><p>Mau ngemil yang gurih, pedas, atau manis? Pilih favoritmu.</p></div><div className="product-grid">{products.map(p=><ProductCard product={p} key={p.name}/>)}</div><a className="center-link" href={orderUrl} target="_blank" rel="noreferrer">Mau lihat semua rasa? Chat kami <b>→</b></a></section>
  <section className="why section" id="kenapa"><div className="shell"><div className="section-heading centered"><p className="eyebrow">ALASAN BUAT TAMBAH LAGI</p><h2>Kenapa <span>KriukLagi?</span></h2></div><div className="feature-grid">{[["✦","Renyah","Kriuk yang terasa di setiap gigitan."],["♨","Bumbu Melimpah","Rasa gurih dan bumbu yang nggak pelit."],["Rp","Harga Bersahabat","Enak buat ngemil tanpa bikin dompet nangis."],["♥","Cocok Kapan Saja","Teman kerja, belajar, santai, atau nonton."]].map(([i,t,d])=><article className="feature" key={t}><div className="feature-icon">{i}</div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="bundle-section section shell"><div className="bundle-intro"><p className="eyebrow">PAKET HEMAT BUAT SEMUA MOOD</p><h2>Lebih Banyak<br /><span>Kriuk, Lebih Hemat</span></h2><p>Isi toples, bekal, atau bagi-bagi bareng teman. Pilih paketmu, kami siapin kriuknya!</p><div className="mini-snacks"><SnackArt variant="red" /></div></div><div className="bundle-grid">{bundles.map(b=><article className={`bundle ${b.featured?"featured":""}`} key={b.name}>{b.featured&&<span className="popular">PALING LARIS ✦</span>}<p>{b.name}</p><h3>{b.quantity}</h3><strong>{rp(b.price)}</strong><span className="bundle-note">lebih hemat buat ngemil</span><a href={waLink(`Halo KriukLagi 👋 Saya mau pesan ${b.name} (${b.quantity}).`)} target="_blank" rel="noreferrer">{b.label} <b>→</b></a></article>)}</div></section>
  <section className="about section" id="tentang"><div className="shell about-grid"><div className="about-art"><Image src="/kriuklagi_logo.png" alt="Logo KriukLagi" width={460} height={460} /><span className="round-text">KRIUK ENAK • SETIAP SAAT • </span></div><div className="about-copy"><p className="eyebrow">DARI KAMI, UNTUK MOMEN NGEMILMU</p><h2>Tentang <span>KriukLagi</span></h2><p>KriukLagi hadir untuk menemani momen ngemil sehari-hari dengan snack yang renyah, enak, dan tetap ramah di kantong.</p><p>Kami percaya snack sederhana bisa membuat hari jadi lebih menyenangkan. Dari satu gigitan, jadi pengen lagi.</p><a href="#cara-pesan" className="text-link">Kenalan lebih dekat <b>→</b></a></div></div></section>
  <section className="steps section" id="cara-pesan"><div className="shell"><div className="section-heading centered"><p className="eyebrow">CUMA 3 LANGKAH</p><h2>Mau Kriuk? <span>Gampang!</span></h2></div><div className="steps-grid">{[["01","Pilih Snack","Pilih produk dan paket favoritmu."],["02","Pesan","Klik tombol WhatsApp dan kirim pesanan."],["03","Terima & Nikmati","Snack dikirim dan siap menemani waktu ngemilmu."]].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div><div className="center"><a className="button" href={orderUrl} target="_blank" rel="noreferrer">◔ Pesan via WhatsApp</a></div></div></section>
  <section className="testimonials section shell"><div className="section-heading"><p className="eyebrow">CERITA DARI PARA PENGGEMAR KRIUK</p><h2>Kata <span>Mereka</span></h2><p className="placeholder-note">Contoh ulasan — akan diganti dengan cerita pelanggan asli.</p></div><div className="testimonial-grid">{["Renyah banget! Bumbunya juga berasa.","Awalnya cuma coba satu, akhirnya pesan lagi 😂","Harganya murah tapi rasanya nggak murahan."].map((q,i)=><blockquote key={q}><div className="stars">★★★★★</div><p>“{q}”</p><footer>— Pelanggan KriukLagi <small>contoh ulasan</small></footer></blockquote>)}</div></section>
  <section className="faq section" id="faq"><div className="shell faq-grid"><div className="section-heading"><p className="eyebrow">BIAR MAKIN YAKIN</p><h2>Pertanyaan yang<br /><span>Sering Ditanyakan</span></h2><p>Masih penasaran? Langsung chat kami aja, ya.</p></div><FAQ /></div></section>
  <section className="final-cta"><div className="shell cta-inner"><div><p className="eyebrow">JANGAN CUMA DIBAYANGIN</p><h2>Udah Kebayang <span>Kriuknya?</span></h2><p>Jangan cuma lihat. Cobain sekarang.</p></div><div className="cta-buttons"><a className="button light" href={orderUrl} target="_blank" rel="noreferrer">Pesan Sekarang <b>→</b></a>{siteConfig.instagram ? <a className="outline-light" href={siteConfig.instagram}>Follow Instagram</a> : <span className="outline-light disabled">Instagram segera hadir</span>}</div></div></section>
  </main><footer className="footer"><div className="shell footer-grid"><div><Image src="/kriuklagi_logo.png" alt="KriukLagi" width={130} height={130}/><p>{siteConfig.tagline}</p></div><div><h3>Jelajahi</h3><a href="#produk">Produk</a><a href="#tentang">Tentang Kami</a><a href="#faq">FAQ</a></div><div><h3>Hubungi Kami</h3><a href={orderUrl} target="_blank" rel="noreferrer">WhatsApp</a><a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>{siteConfig.marketplace ? <a href={siteConfig.marketplace}>Marketplace</a> : <span>Marketplace segera hadir</span>}</div></div><div className="shell copyright">© {new Date().getFullYear()} KriukLagi. Dibuat untuk waktu ngemil yang lebih seru.</div></footer>
  <a className="mobile-wa" href={orderUrl} target="_blank" rel="noreferrer">◔ Pesan KriukLagi via WA <b>→</b></a>
  </>;
}
